# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'fileutils'

default_platform(:ios)

platform :ios do
  lane :clean_dirs do
    FileUtils.rm_rf('derived_data')
    FileUtils.rm_rf('xcov_output')
  end

  lane :build_and_test do
    setup_ci if ENV['CI']
    run_tests
    puts "SHARED VAR VALUE"
    puts Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
  end
end
