name: Distribute to Firebase

on:
  push:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  review_pull_request:
    name: Distribute IPA using Firebase
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./Survey/
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      id: bunlderCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: bundle install --path vendor/bundle

    - name: Cache Pods
      uses: actions/cache@v2
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install Pods Dependencies
      run: bundle exec pod install
   
    - name: Clean up previous code coverage report
      run: bundle exec fastlane clean_dirs

    - name: Distribute ipa
      run: bundle exec fastlane distribute_firebase
      env:
        CI: true
